language: php

services: docker

php:
  - 5.5
  - 5.6
  - hhvm

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --prefer-source --no-interaction --dev
  - git clone https://github.com/yousan/damp.git
  - cd damp; docker-compose up -d
  - docker-compose ps

script: phpunit
