language: php

services: docker

php:
  - 5.5
  - 5.6
  - hhvm

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --prefer-source --no-interaction --dev
  - nslookup test.dev
#  - curl -s -L -o - https://raw.githubusercontent.com/yousan/damp/master/docker-compose.yml | sed -e 's/#      - ~\/public_html:\/var\/www\/vhosts/      - ~\/public_html:\/var\/www\/vhosts/g' | docker-compose -f - up
#  - docker-compose ps

script:
 - phpunit
